version: '3.8'

services:
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./log:/app/src/log

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./log:/app/logs
    command: ["--game.state-service.url=http://engine:5000/api/neuroshima"]
    depends_on:
      - engine
