# URL serwisu stanu gry u?ywanego przy tworzeniu nowej gry
# game.state-service.url=http://127.0.0.1:5000/api/neuroshima

# Plik z u?ytkownikami (format: username:{id}hash lub username:haslo)
auth.users.file=users.txt

# Czas ?ycia tokenu logowania dla WebSocket (sekundy)
auth.token.ttl-seconds=3600

# Typ repozytorium u?ytkownik?w: 'db' (domy?lnie) lub 'file'
app.user-repository=db

# Konfiguracja bazy danych SQLite
spring.datasource.url=jdbc:sqlite:db/users.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Konfiguracja JPA/Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
